on: [push]

jobs:
  my-job:
    runs-on: unbuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: run the action
      id: hello
      uses: ./
      with:
        myInput: 'Stephen'
    -name: output the memory
      run: |
        echo ${{ steps.hello.outputs.memory }}
        echo "total memory succesully output"
